before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
- sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
- sudo apt-get update
- sudo apt-get -y install qt5-default qtdeclarative5-dev
- sudo apt-get -y install qtdeclarative5-test-plugin pep8 pyflakes
- sudo apt-get -y install qtdeclarative5-qtquick2-plugin
script:
- qmake
- make check
