before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
- sudo add-apt-repository -y ppa:beineri/opt-qt532
- sudo apt-get update
- sudo apt-get -y install qt53declarative
- sudo apt-get -y install pep8 pyflakes
- sudo apt-get -y install qt53quickcontrols
- sudo apt-get -y install qt53tools
- /opt/qt53/bin/qt53-env.sh
script:
- qmake
- make check
